CREATE DATABASE IF NOT EXISTS pixelpaint95 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE pixelpaint95;

CREATE TABLE IF NOT EXISTS pixels (
  x INT NOT NULL,
  y INT NOT NULL,
  color TINYINT UNSIGNED NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (x, y)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pixel_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  x INT NOT NULL,
  y INT NOT NULL,
  color TINYINT UNSIGNED NOT NULL,
  ip_hash CHAR(64) NOT NULL,
  ts TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_ts (ts)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rate_limits (
  ip_hash CHAR(64) NOT NULL,
  next_allowed_ts TIMESTAMP(6) NOT NULL DEFAULT '1970-01-01 00:00:00.000000',
  PRIMARY KEY (ip_hash)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nick VARCHAR(32) NOT NULL,
  token CHAR(64) NOT NULL,
  cooldown_override_seconds INT NULL DEFAULT NULL, -- NULL=по умолчанию, 0=без кулдауна, >0=свой интервал
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_ip_hash CHAR(64),
  PRIMARY KEY (id),
  UNIQUE KEY uniq_token (token),
  KEY idx_ip (last_ip_hash)
) ENGINE=InnoDB;
